config/routes.rb
Rails.application.routes.draw do
  get 'fonts/*ttf', to: 'fonts#materialdesignicons_webfont'
  get 'login', to: 'login#login', as: 'login'
  get 'signup', to: 'login#signup', as: 'signup'
  post 'create-session', to: 'login#create_session', as: 'create_session'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model_tag.rb
class ModelTag < ApplicationRecord
  belongs_to :model, polymorphic: true
  belongs_to :tag
end

app/models/series.rb
class Series < ApplicationRecord
  belongs_to :user

  has_many :model_tags, as: :model
  has_many :tags, through: :model_tags

  has_many :story_series
  has_many :stories, through: :story_series

  validates :name, :description, :user_id, presence: true

  has_one_attached :cover_image
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user

  has_many :model_tags, as: :model
  has_many :tags, through: :model_tags

  has_one :story_series
  has_one :series, through: :story_series

  validates :title, :slug, :user_id, :unique_id, presence: true

  has_rich_text :content
  has_one_attached :cover_image

  has_many_attached :images

  before_validation :setup_uniqueness

  def generate_unique_id
    rand(65536)
  end

  def generate_slug
    base = self.title.downcase
    sanitized = base.gsub(/\W/, '-')
    id = self.unique_id.to_s(16)
    sanitized + "-#{id}"
  end

  def setup_uniqueness
    self.unique_id = generate_unique_id if self.unique_id == 0
    self.slug = generate_slug
  end
end

app/models/story_series.rb
class StorySeries < ApplicationRecord
  belongs_to :story
  belongs_to :series
  
  validates :story_id, unique: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :stories
    has_many :series

    validates :name, :email, :username, presence: true
    validates :username, uniqueness: true

    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if logged_in?
    end

    def require_login
        redirect_to login_path if !logged_in?
        current_user
    end
end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  def materialdesignicons_webfont
    send_file(Rails.root.join('node_modules', '@mdi', 'font', 'fonts', "#{params[:ttf]}.ttf"))
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end

  def create_session
    user = User.find_by(username: login_params[:username])
    if user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to login_path
    end
  end

  def signup
    @user = User.new
  end

  private

  def login_params
    params.permit(:username, :password)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    before_action :require_login

    def new
        @story = Story.new
    end

    def create
      @story = Story.new(story_params)

      @story.user_id = @current_user.id
      if @story.save
        redirect_to story_path(@story)
      else
        redirect_to new_story_path
      end
    end

    def show
        @story = Story.find_by(slug: params[:id])
    end

    def edit
        @story = Story.find_by(story: params[:id])
    end

    def update
        if @story.update(story_params)
            redirect_to story_path(@story)
        else
            redirect_to edit_story_path(@story)
        end
    end

    def delete

    end

    private

    def story_params
      params.require(:story).permit(:title, :content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
        user = User.new(signup_params)

        if user.save
            session[:user_id] = user.id
            redirect_to '/'
        else
            render 'login/signup'
        end
    end


    private

    def signup_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/controls/_input.html.erb
<div class="field">
    <label class="label" for="<%= id ||= "" %>"><%= label_text %></label>
    <div class="control">
        <input 
            class="input" 
            type="<%= type ||= "text" %>"
            id="<%= id ||= "" %>"
            placeholder="<%= placeholder ||= ""%>" 
            value="<%= value ||= "" %>"
            name="<%= name ||= "" %>"
        >
    </div>
</div>

app/views/controls/_password.html.erb
<div class="field">
    <%= form.label attribute, label, class: "label" %>
    <div class="control">
        <%= form.password_field attribute, class: "input", placeholder: placeholder %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prescion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="section">
      <%= yield %>
    </main>
  </body>
</html>

app/views/login/login.html.erb
<section class="container">
    <div class="box">
        <h1 class="title">Enter your Login Info</h1>
        <%= form_with url: create_session_path do |form| %>
            <%= render partial: "controls/input", locals: {
                form: form,
                attribute: :username,
                label: "Username",
                placeholder: 'Username'
            }%>

            <%= render partial: "controls/password", locals: {
                form: form,
                attribute: :password,
                label: 'Password',
                placeholder: 'Password'
            } %>

            <%= form.submit "Login", class: "button is-info" %>
        <% end %>
    </div>
</section>

app/views/login/signup.html.erb
<section class="container">
    <div class="box">
        <h1 class="title">Please Enter your details to sign up</h1>
        <%= form_with model: @user do |form| %>
            <%= render partial: 'controls/input', locals: {
                form: form,
                attribute: :name,
                label: 'Full Name',
                placeholder: 'Jon Doe',
            }%>

            <%= render partial: 'controls/input', locals: {
                form: form,
                attribute: :username,
                label: "Username",
                placeholder: "Username",
            }%>

            <%= render partial: 'controls/input', locals: {
                form: form,
                attribute: :email,
                label: 'Email Address',
                placeholder: 'hello@world.org',
            }%>

            <%= render partial: 'controls/password', locals: {
                form: form,
                attribute: :password,
                label: 'Password',
                placeholder: 'Password',
            }%>

            <%= render partial: 'controls/password', locals: {
                form: form,
                attribute: :password_confirmation,
                label: 'Confirm Password',
                placeholder: 'Confirm Password',
            }%>

            <%= form.submit "Sign Up", class: 'button is-info'%>
        <% end %>
    </div>
</section>

app/views/stories/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">New Story</h1>
    <div class="content">
      <%= form_with model: @story do |form| %>
        <%= render partial: "controls/input", locals: {
          form: form,
          attribute: :title,
          label: "Title",
          placeholder: "Title"
        } %>
        <%= form.rich_text_area :content %>
        <%= form.submit "Create Story" %>
      <% end %>
    </div>
  </div>
</section>